version: "3"
services:
    web-app-service:
        image: sentiment_classification_webapp:1.0
        depends_on: 
            text-classification-service:
                condition: service_healthy
        stdin_open: true
        tty: true
        ports:
            - "8501:8501"

    text-classification-service:
        image: sentiment_classification_service:1.0
        stdin_open: true
        tty: true
        ports:
            - "9090:9090"
        volumes:
            - ${PWD}:${PWD}
            - ./.trained-models:/service/.trained-models

